<!-- div style="margin: 0 0 5rem 0 !important;"></div -->

<div class="container">
	<div class="row">
		<div class="text-center">
			<h1>Join Us And Contribute Now!</h1>
			<div class="col-md-6 text-center">
				<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
				<input type="hidden" name="cmd" value="_s-xclick">
				<input type="hidden" name="hosted_button_id" value="ZPHYHYTE52LBN">
				Contribution Levels<br>
				<select name="os0">
					<option value="Option 1">Option 1 $10.00 USD</option>
					<option value="Option 2">Option 2 $25.00 USD</option>
					<option value="Option 3">Option 3 $50.00 USD</option>
					<option selected value="Option 4">Option 4 $99.00 USD</option>
					<option value="Option 5">Option 5 $400.00 USD</option>
					<option value="Option 6">Option 6 $800.00 USD</option>
					<option value="Option 7">Option 7 $5,000.00 USD</option>
					<option value="Option 8">Option 8 $90,000.00 USD</option>
				</select>
				<br>
				<input type="hidden" name="currency_code" value="USD">
				<input type="image" src="http://thegivingcycle.org/images/contribute-button-150x51.png" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
				<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
				</form>
			</div>
			<div class="col-md-6 text-center">
                        	<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                        	<input type="hidden" name="cmd" value="_s-xclick">
                        	<input type="hidden" name="hosted_button_id" value="F7AAJZWTLC97U">
				Contribution Any Amount<br>
                        	<input type="image" src="http://thegivingcycle.org/images/contribute-button-150x51.png" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                        	<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                        	</form>
                        	<!-- a href="contribute.php" target="_blank"><img src="images/contribute-button-150x51.png" alt="Contribute"></a -->
			</div><br>
		</div>
	</div>
	<div class="row">
		<div class="text-center">
			<p class="lead">We know You are generous or You wouldn't be here. Nevertheless, You may contribute any amount You choose. We are trying to raise a total of $90,000.00. A $99 contribution makes You an automatic full founding member, and locks in Your annual membership price at $99 per year for life. By making such a contribution during our pre-launch, Your membership is automatically paid up through December 31, 2017! Founding members receive other special benefits, as well (see above).</p>
			<p class="lead">If you would like more information about the benefits of founding membership, <a href="aboutus.php" target="_blank">click here to learn more</a>.</p>
		</div>
	</div><!-- /.row -->
</div><!-- /.container -->

