<div style="margin: 0 0 5rem 0 !important;"></div>

<!-- div id="footer" class="navbar-fixed-bottom" style="background-color:#333333;" -->
<div id="footer" class="navbar-fixed-bottom" style="background-color:#333333;">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<a href="/">&copy; 2016 The Giving Cycle&trade;</a><br>
				<a target="_blank" href="privacy.php">Privacy</a> | <a target="_blank" href="terms.php">Terms</a> | <a target="_blank" href="refunds.php">Refunds</a> | <a target="_blank" href="members/register.php">Become a Member</a> | <a target="_blank" href="members/index.php">Member Login</a>
			</div>
		</div>
	</div>
</div>

