<ul class="topnav">
  <li><a class="active" href="../indexmain.php">Home</a></li>
  <li><a href="../about.php">About</a></li>
  <li><a href="../connect.php">Connect</a></li>
  <li><a href="../gain.php">Gain</a></li>
  <li style="float:right"><a class="active" href="../contact/index.php">Contact Us</a></li>
  <li style="float:right"><a class="active" href="../terms.php">Use Policy</a></li>
  <li style="float:right"><a class="active" href="../privacy.php">Privacy Policy</a></li>
  <li style="float:right"><a class="active" href="index.php">Login</a></li>
  <li class="icon">
    <a href="javascript:void(0);" style="font-size:15px;" onclick="myFunction()">Menu</a>
  </li>
</ul>
