<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
                <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"><img src="images/brand.png"></a>
                </div>
                <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                                <li class="active"><a href="index.php">Home</a></li>
                                <!-- li><a target="_blank" href="index.live.php">More Info</a></li -->
                                <li><a target="_blank" href="aboutus.php">About Us</a></li>
                                <li><a target="_blank" href="contribute.php">Contribute</a></li>
                                <li><a target="_blank" href="contact">Contact Us</a></li>
                        </ul>
                </div><!--/.nav-collapse -->
        </div>
</div>

